import AdminSidebar from "@/components/AdminSidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <div lang="en" className="flex">
      <AdminSidebar />
      <div>{children}</div>
    </div>
  );
}
