import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/contexts/AuthContext";
import { Poppins,Roboto,Montserrat,Halant } from 'next/font/google';  // Import Google Fonts

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],  // Choose the subsets you need
  weight: ['400', '500', '700'],  // Specify the weights
  display: 'swap',
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});
const halant = Halant({
  subsets: ['latin'],
  weight: ['300', '400','500'],  // Regular and Bold weights
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
